### ISSUE TITLE
How to use own data

### ISSUE THREAD

**Issue by nullhty** [csmliu/STGAN#15]
I want to removal the eyegalsses on my own face image. I find use the model which training on CeleA will not work. So, I use own data to train the model. However, it still not work. The image looks like the reconstruction image which the attribute about eyeglasses is not be changed. I want to get some suggestion about training the model. How many images should be prepared for training. I only use 40000 images with eyeglasses and without eyegalsses

**Comment by CastellanLiu** [comment]
The model is trained on aligned CelebA dataset (thus should not work on images with arbitrary pose), and is not very good at removing eyeglasses (especially sunglasses) since it is actually an inpainting task.
If you want to train with your own data, you can modify `data.py`. But I have no idea about the quantity of images required, and removing eyeglasses on images with arbitrary pose is much harder than on aligned images.
BTW, maybe you can try some inpainting methods especially those designed for facial images (along with a segmentation model to mask the eyeglasses).

**Comment by nullhty** [comment]
> The model is trained on aligned CelebA dataset (thus should not work on images with arbitrary pose), and is not very good at removing eyeglasses (especially sunglasses) since it is actually an inpainting task.
> If you want to train with your own data, you can modify `data.py`. But I have no idea about the quantity of images required, and removing eyeglasses on images with arbitrary pose is much harder than on aligned images.
> BTW, maybe you can try some inpainting methods especially those designed for facial images (along with a segmentation model to mask the eyeglasses).

I am not really understand the theory about attribute editing. If I want to removal eyeglasses, but I use the man with eyeglasses and women without eyeglasses to train the model. How does the model distinguish whether the attribute label is for sex or eyeglasses?

**Comment by csmliu** [comment]
The model learns what `gender` and `eyeglasses` are from the data, i.e., images with attributes `man w/wo eyeglasses`, `woman w/wo eyeglasses`.
In your case, the model would link `male` with `eyeglasses`, then both eyeglasses and gender will be converted.

**Comment by nullhty** [comment]
> The model learns what `gender` and `eyeglasses` are from the data, i.e., images with attributes `man w/wo eyeglasses`, `woman w/wo eyeglasses`.
> In your case, the model would link `male` with `eyeglasses`, then both eyeglasses and gender will be converted.

Thanks! Your answer is very helpful to me.
