### ISSUE TITLE
testing images outside test set

### ISSUE THREAD

**Issue by ak9250** [csmliu/STGAN#2]
can you test images outside the test celebA test set?

**Comment by csmliu** [comment]
Hi ak9250, since the images are aligned and cropped when training and testing on the CelebA dataset, it's a bit complex to test on other images.
One of my labmates asked the same question before, so I modified the code, prepared an attribute label file manually and tested on the images he gave me without alignment. The results show that the model still works on some attributes like `hair color', but gets poor results on other attributes.
If you are interested, maybe you could align the images and prepare an attribute label file for the image. To align the images, [HD-CelebA-Cropper@LynnHo](https://github.com/LynnHo/HD-CelebA-Cropper) may help.
