### ISSUE TITLE
Question about STU structure

### ISSUE THREAD

**Issue by XijieJiao** [csmliu/STGAN#43]
Hi, thank you for sharing your project. 
Do you think it is possible to add noise to interfere with the generation of desired attribute like glasses in order to have varied attribute(glasses)'s style?

Along with the previous question, I visualized the nodes in different parts of the model. It seems that glasses are generated in STU, so I think it might work if I add noise just one step before the glasses (information or shape of it) are generated. Could you give me some idea where should be the place the attribute is first generated (there are dozens of nodes in STU and there are four STUs)?

Thank you!

**Comment by csmliu** [comment]
Hi Xijie,

I think that CNNs tend to make full use of all parameters (especially for a hard task), thus it could be the effect of the whole network. However, the manipulation should start at the innermost STU, since the desired attribute is first introduced here, which also verifies your observation.

As for attribute style controlling, I agree with the idea to add noise, but the core problem is how to automatically group or divide the styles. Otherwise the noise will have no relationship with the style (well, it may enhance some details, but that's not what  you want).

Maybe you could refer to AttGAN for style manipulation. But it seems that the relevant code is not released yet.

Best,
Ming
